services:
  vite-app:
    build: 
      context: .
    ports:
      - "8084:80"
    volumes:
      - ./dist:/usr/share/nginx/html/2025-bandwaggon-website-typescript
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:  # Cambiado de 'expose' a 'ports'
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
